import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Print Race Card",
  description: "Printable race day nutrition card generated by Ultra Fuel Planner.",
  robots: {
    index: false,
    follow: false,
  },
};

export default function PrintLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
